CREATE TABLE IF NOT EXISTS accounts
(
    id           bigint primary key generated by default as identity,
    name         varchar(255) not null,
    phone_number varchar(20)  not null,
    address      varchar(510) not null,
    city_id      bigint       not null,
    created_at   timestamp default now(),
    updated_at   timestamp default now(),
    deleted_at   timestamp
);

CREATE TABLE IF NOT EXISTS cities
(
    id         bigint primary key generated by default as identity,
    name       varchar(255) not null,
    location   point        not null,
    created_at timestamp default now(),
    updated_at timestamp default now(),
    deleted_at timestamp
);

CREATE TABLE IF NOT EXISTS products
(
    id         bigint primary key generated by default as identity,
    account_id bigint         not null,
    city_id    bigint         not null,
    model_id   bigint         not null,
    year       integer        not null,
    price      numeric(20, 2) not null,
    created_at timestamp default now(),
    updated_at timestamp default now(),
    deleted_at timestamp,
    CONSTRAINT fk_product_account
        FOREIGN KEY (account_id)
            REFERENCES accounts (id),
    CONSTRAINT fk_product_model
        FOREIGN KEY (model_id)
            REFERENCES models (id),
    CONSTRAINT fk_product_city
        FOREIGN KEY (city_id)
            REFERENCES cities (id)
);

CREATE TABLE IF NOT EXISTS brands
(
    id         bigint primary key generated by default as identity,
    name       varchar(510) not null,
    created_at timestamp default now(),
    updated_at timestamp default now(),
    deleted_at timestamp
);

CREATE TABLE IF NOT EXISTS types
(
    id         bigint primary key generated always as identity,
    name       varchar(510) not null,
    created_at timestamp default now(),
    updated_at timestamp default now(),
    deleted_at timestamp
);

CREATE TABLE IF NOT EXISTS models
(
    id         bigint primary key generated always as identity,
    brand_id   bigint       not null,
    type_id    bigint       not null,
    name       varchar(510) not null,
    created_at timestamp default now(),
    updated_at timestamp default now(),
    deleted_at timestamp,
    CONSTRAINT fk_model_brand
        FOREIGN KEY (brand_id)
            REFERENCES brands (id),
    CONSTRAINT fk_model_type
        FOREIGN KEY (type_id)
            REFERENCES types (id)
);

CREATE TABLE IF NOT EXISTS bids
(
    id         bigint primary key generated always as identity,
    account_id bigint         not null,
    product_id bigint         not null,
    price      numeric(20, 2) not null,
    status     varchar(510)   not null,
    created_at timestamp default now(),
    updated_at timestamp default now(),
    deleted_at timestamp,
    CONSTRAINT fk_bids_account
        FOREIGN KEY (account_id)
            REFERENCES accounts (id),
    CONSTRAINT fk_bids_product
        FOREIGN KEY (product_id)
            REFERENCES products (id)
);
